name: Pullrequest

on:
    pull_request

jobs:
    check:
        runs-on: ubuntu-latest
        permissions:
          contents: read
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/

            - name: Install Dependencies
              run: npm install

            - name: Check
              run: npm run check

            - name: Build
              run: npm run build
